import type { Metadata } from "next"
import "./globals.css"
import { ThemeProvider } from "~/components/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className="flex min-h-dvh flex-col p-4 antialiased">
          <header className="flex h-16 items-center">
            <div className="w-32 text-start">icons</div>
            <div className="flex-1 text-center">navigation</div>
            <div className="w-32 text-end">func-btn</div>
          </header>
          <main className="flex-1 px-4">{children}</main>
          <footer className="flex items-end">
            <div className="flex-1 text-center">footer</div>
          </footer>
        </body>
      </ThemeProvider>
    </html>
  )
}
