import type { Metadata } from "next"
import "./globals.css"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" data-oid="v2jflgg">
      <body className="antialiased" data-oid="d9py1bc">
        {children}
      </body>
    </html>
  )
}
